// TERMINAL SESSION — components.js
var h=React.createElement,useState=React.useState,useEffect=React.useEffect,useRef=React.useRef,useCallback=React.useCallback;

function Boot(p){
  var s=useState([]),lines=s[0],setLines=s[1];var s2=useState(false),done=s2[0],setDone=s2[1];var idx=useRef(0);
  useEffect(function(){var t=setInterval(function(){if(idx.current<BOOT_LINES.length){setLines(function(p){return p.concat([BOOT_LINES[idx.current]])});idx.current++}else{clearInterval(t);setTimeout(function(){setDone(true)},800)}},280);return function(){clearInterval(t)}},[]);
  return h('div',{className:'boot'},h('div',{className:'boot-text',style:{fontFamily:"'Share Tech Mono',monospace",fontSize:13,lineHeight:1.9,maxWidth:420,width:'100%'}},lines.map(function(l,i){var s=String(l||'');return h('div',{key:i,style:{color:s.indexOf('TERMINAL SESSION')>=0?'#f0a030':s.indexOf('WELCOME')>=0?'#50ff50':'#33ff33',fontWeight:s.indexOf('TERMINAL')>=0||s.indexOf('WELCOME')>=0?'bold':'normal',whiteSpace:'pre-wrap',animation:'slideUp 0.3s ease'}},s)}),!done&&h('span',{style:{animation:'blink 1s infinite'}},'█')),done&&h('button',{className:'btn',onClick:p.onDone},'[ 세션 시작 ]'));
}
function Stats(p){
  var sm=[{k:'c',l:'봉쇄',ic:'◆'},{k:'r',l:'자원',ic:'◇'},{k:'t',l:'신뢰',ic:'○'},{k:'o',l:'평가',ic:'●'}];
  return h('div',{className:'stats'},h('div',{className:'stats-hdr'},'ORACLE STATUS — DAY '+p.stats.day),sm.map(function(s){var v=p.stats[s.k],d=v<=15,hi=v>=85,c=d?'#ff4444':hi&&s.k==='o'?'#f0a030':'#33ff33';return h('div',{key:s.k,className:'stat-row'},h('span',{className:'stat-label',style:{color:c}},s.ic+' '+s.l),h('div',{className:'bar-bg'},h('div',{className:'bar-fill',style:{width:v+'%',background:c}})),h('span',{className:'stat-val',style:{color:d?'#ff4444':'#33ff33'}},v))}));
}
function CardC(p){
  var card=p.card,gi=p.gi||0;
  var s1=useState(0),dx=s1[0],setDx=s1[1];var s2=useState(false),dragging=s2[0],setDragging=s2[1];var s3=useState(0),sx=s3[0],setSx=s3[1];var s4=useState(null),chosen=s4[0],setChosen=s4[1];var s5=useState(false),isGlitch=s5[0],setIsGlitch=s5[1];
  useEffect(function(){setIsGlitch(gi<=30&&(p.day||1)>=5&&Math.random()>0.7)},[card]);
  var th=80,dir=dx>th?'right':dx<-th?'left':null,tx=chosen==='left'?-400:chosen==='right'?400:dx;
  var hS=function(x){setSx(x);setDragging(true)},hM=function(x){if(dragging)setDx(x-sx)};
  var hE=function(){setDragging(false);if(dir){setChosen(dir);setTimeout(function(){p.onSwipe(dir);setDx(0);setChosen(null)},300)}else setDx(0)};
  var pc=card.priority==='상'?'#ff4444':card.priority==='중'?'#f0a030':'#33ff33';
  return h('div',{className:'card-area'},
    h('div',{className:'hint hint-l',style:{opacity:dx<-30?Math.min(1,Math.abs(dx)/th):0}},'← '+card.left.label),
    h('div',{className:'hint hint-r',style:{opacity:dx>30?Math.min(1,dx/th):0}},card.right.label+' →'),
    h('div',{className:'card'+(isGlitch?' screen-glitch':''),style:{transform:'translateX('+tx+'px) rotate('+(tx*0.04)+'deg)',transition:dragging?'none':'transform 0.3s ease',opacity:chosen?0:1,borderColor:dir==='left'?'#f0a030':dir==='right'?'#33ff33':isGlitch?'#440000':'#1a3a1a'},
      onMouseDown:function(e){hS(e.clientX)},onMouseMove:function(e){hM(e.clientX)},onMouseUp:hE,onMouseLeave:function(){if(dragging)hE()},
      onTouchStart:function(e){hS(e.touches[0].clientX)},onTouchMove:function(e){e.preventDefault();hM(e.touches[0].clientX)},onTouchEnd:hE},
      h('div',{className:'card-hdr'+(isGlitch?' glitch-active':''),style:{borderBottomColor:pc}},h('span',null,'ORACLE 통신'),h('span',{style:{color:pc}},'우선순위: '+card.priority)),
      h('div',{className:'card-body'+(isGlitch?' glitch-active':'')},card.msg),
      h('div',{className:'card-ft'},h('span',null,'← '+card.left.label),h('span',null,card.right.label+' →'))
    ));
}
function News(p){
  var s=useState(0),shown=s[0],setShown=s[1];var bg=Math.random()>0.5?IMG.bg_seoul_a:IMG.bg_seoul_b;
  useEffect(function(){if(shown<p.headlines.length){var t=setTimeout(function(){setShown(function(v){return v+1})},600);return function(){clearTimeout(t)}}},[shown,p.headlines.length]);
  return h('div',{className:'news',style:{position:'relative'}},bg&&h('div',{className:'bg-overlay',style:{backgroundImage:'url('+bg+')',opacity:0.15,height:120,left:0,right:0,width:'100%'}}),h('div',{className:'news-hdr'},'ORACLE 정보 수신'),h('div',{style:{color:'#1a3a1a',textAlign:'center',marginBottom:20}},'━━━━━━━━━━━━━━━━━━━━━━━━━'),p.headlines.slice(0,shown).map(function(l,i){var s=String(l||'');return h('div',{key:i,className:'news-line'+(s.indexOf('분류 오류')>=0?' news-glitch':'')+(s.indexOf('삭제됨')>=0?' news-deleted':'')},s)}),shown>=p.headlines.length&&h('button',{className:'btn',style:{display:'block',margin:'24px auto 0'},onClick:p.onContinue},'[ 다음 날 ]'));
}
function GameOver(p){
  var msg=p.gi>50?"요원의 헌신적 복무에 감사드립니다.":p.gi>25?"세션이 종료됩니다. 결과가 기록되었습니다.":"비표준 운영 패턴 감지. 세션 데이터 분석 중...";
  return h('div',{className:'boot'},h('div',{style:{fontSize:13,lineHeight:1.9,maxWidth:420,width:'100%',textAlign:'center'}},h('div',{className:'go-title'},'─── SESSION TERMINATED ───'),h('div',{className:'go-reason'},p.reason),h('div',{className:'go-section'},'── ORACLE 최종 보고 ──'),h('div',{className:'go-stat'},'운영 기간: '+p.stats.day+'일'),h('div',{className:'go-stat'},'봉쇄: '+p.stats.c+' | 자원: '+p.stats.r+' | 신뢰: '+p.stats.t+' | 평가: '+p.stats.o),h('div',{className:'go-msg'},'"'+msg+'"')),h('button',{className:'btn btn-amber',onClick:p.onRestart},'[ 세션 재개시 ]'),h('div',{style:{display:'flex',gap:10,marginTop:16}},h('button',{className:'btn',style:{fontSize:12,padding:'10px 18px',minHeight:44,marginTop:0},onClick:p.onLogs},'기록'),h('button',{className:'btn',style:{fontSize:12,padding:'10px 18px',minHeight:44,marginTop:0},onClick:p.onEndings},'엔딩')));
}
function Tutorial(p){
  var s1=useState(0),step=s1[0],setStep=s1[1];
  var steps=[{lines:["ORACLE 인사 프로토콜을 개시합니다.","","환영합니다, 이중철 지휘관.","","당신은 Proxy Network 한국 지부의","초대 지휘관으로 발령되었습니다.","","본 지부는 강원도 내 비공개 위치에","설치된 최초의 한국 거점입니다."],choices:[{label:"발령을 수락합니다",next:1},{label:"상세 브리핑을 요청합니다",next:1}]},{lines:["대한민국은 EV-Σ 위기 속에서","안정적인 봉쇄 체계를 유지하고 있는","몇 안 되는 국가 중 하나입니다.","","지휘관으로서 당신의 역할은","기지 운영과 현장 임무를 총괄하는 것입니다."],choices:[{label:"계속",next:2}]},{lines:["지휘관은 4가지 핵심 지표를 관리해야 합니다.","","◆ 봉쇄 — 관할 구역 봉쇄선 유지도","◇ 자원 — 식량, 의약품, 장비","○ 신뢰 — 기지 인원의 신뢰도","● 평가 — ORACLE의 당신에 대한 평가","","어느 지표든 0이 되면 임무에 실패합니다."],choices:[{label:"이해했습니다",next:3}]},{lines:["매일 ORACLE이 보고서와 요청을 전달합니다.","","카드를 좌우로 밀어 결정을 내리십시오.","","← 왼쪽: 첫 번째 선택지","→ 오른쪽: 두 번째 선택지"],choices:[{label:"임무를 시작합니다",next:-1}]}];
  var st=steps[step];var s2=useState(0),shown=s2[0],setShown=s2[1];var s3=useState(false),bv=s3[0],setBv=s3[1];
  useEffect(function(){setShown(0);setBv(false)},[step]);
  useEffect(function(){if(shown<st.lines.length){var t=setTimeout(function(){setShown(function(v){return v+1})},st.lines[shown]===''?150:80);return function(){clearTimeout(t)}}else{var t2=setTimeout(function(){setBv(true)},400);return function(){clearTimeout(t2)}}},[shown,step]);
  return h('div',{className:'screen'},h('div',{style:{width:'100%',maxWidth:420,padding:'40px 0',flex:1,display:'flex',flexDirection:'column'}},h('div',{style:{fontFamily:"'Share Tech Mono',monospace",fontSize:11,color:'#1a6a1a',textAlign:'center',marginBottom:16,letterSpacing:2}},'ORACLE BRIEFING — '+(step+1)+'/'+steps.length),h('div',{style:{flex:1,display:'flex',flexDirection:'column',justifyContent:'center'}},st.lines.slice(0,shown).map(function(l,i){var txt=String(l||' '),isIcon='◆◇○●'.split('').some(function(c){return txt.indexOf(c)>=0});return h('div',{key:step+'-'+i,style:{fontSize:isIcon?13:14,lineHeight:1.8,color:isIcon?'#f0a030':txt.indexOf('←')>=0?'#33ff33':'#ccddcc',textAlign:'center'}},txt)})),bv&&h('div',{style:{display:'flex',flexDirection:'column',gap:10,alignItems:'center',paddingBottom:20}},st.choices.map(function(c,i){return h('button',{key:i,className:'btn'+(i===0?' btn-amber':''),onClick:function(){if(c.next===-1)p.onDone();else setStep(c.next)}},c.label)}))));
}
function RewardScreen(p){
  var count=3;if(p.stats.c<30||p.stats.r<30||p.stats.t<30||p.stats.o<30)count=2;if(p.stats.c<15||p.stats.r<15||p.stats.t<15||p.stats.o<15)count=1;
  var av=pickN(REWARDS,count);
  return h('div',{className:'screen'},h(Stats,{stats:p.stats}),h('div',{style:{flex:1,width:'100%',maxWidth:420,padding:'20px 0',overflowY:'auto'}},h('div',{style:{fontFamily:"'Share Tech Mono',monospace",fontSize:12,color:'#f0a030',letterSpacing:2,textAlign:'center',marginBottom:6}},'ORACLE 자원 배분'),h('div',{style:{fontSize:13,color:'#ccddcc',textAlign:'center',marginBottom:20}},count===3?'3개 중 1개를 선택하십시오':count===2?'자원 부족 — 2개 중 선택':count===1?'긴급 상황 — 1건':'선택'),av.map(function(r){return h('div',{key:r.id,onClick:function(){p.onPick(r)},style:{background:'#0d1a0d',border:'1px solid #1a3a1a',borderRadius:4,padding:'14px 16px',marginBottom:10,cursor:'pointer'}},h('div',{style:{fontSize:14,color:'#33ff33',fontWeight:'bold',marginBottom:6}},r.title),h('div',{style:{fontSize:12,color:'#88aa88',marginBottom:8,lineHeight:1.6}},r.desc),h('div',{style:{display:'flex',justifyContent:'space-between',fontSize:12}},h('span',{style:{color:'#33ff33'}},'▲ '+r.benefit),h('span',{style:{color:'#ff6644'}},'▼ '+r.cost)))})));
}
function Dialogue(p){
  var d=p.dialogue,portrait=CHAR_IMG[d.char]||null;var s1=useState(0),li=s1[0],setLi=s1[1];var s2=useState(false),sc=s2[0],setSc=s2[1];
  useEffect(function(){setLi(0);setSc(false)},[d]);
  useEffect(function(){if(li<d.lines.length){var t=setTimeout(function(){setLi(function(v){return v+1})},800);return function(){clearTimeout(t)}}else{var t2=setTimeout(function(){setSc(true)},400);return function(){clearTimeout(t2)}}},[li]);
  return h('div',{className:'screen'},h('div',{style:{flex:1,width:'100%',maxWidth:420,padding:'20px 0',display:'flex',flexDirection:'column'}},h('div',{style:{textAlign:'center',marginBottom:16}},portrait&&h('img',{src:portrait,className:'portrait',alt:d.char,style:{width:110,height:110}}),h('div',{style:{fontSize:16,color:'#f0a030',fontWeight:'bold'}},d.char),h('div',{style:{fontFamily:"'Share Tech Mono',monospace",fontSize:11,color:'#1a6a1a',marginTop:4}},d.role)),h('div',{style:{flex:1,display:'flex',flexDirection:'column',justifyContent:'center',padding:'0 8px'}},d.lines.slice(0,li).map(function(l,i){return h('div',{key:i,style:{fontSize:14,lineHeight:1.9,color:'#ccddcc',marginBottom:8,paddingLeft:16,borderLeft:'2px solid #1a5a1a'}},String(l))})),sc&&h('div',{style:{display:'flex',flexDirection:'column',gap:10,alignItems:'center',paddingBottom:20}},d.choices.map(function(c,i){return h('button',{key:i,className:'btn'+(i===0?' btn-amber':''),style:{fontSize:13,padding:'10px 20px',width:'80%',maxWidth:300,marginTop:0},onClick:function(){p.onChoice(c)}},c.label)}))));
}
function LogViewer(p){
  var s1=useState(null),sel=s1[0],setSel=s1[1];var ul=ORACLE_LOGS.filter(function(l){return p.unlockedIds.indexOf(l.id)>=0}),lk=ORACLE_LOGS.length-ul.length;
  if(sel){var log=ORACLE_LOGS.filter(function(l){return l.id===sel})[0];return h('div',{className:'screen'},h('div',{style:{width:'100%',maxWidth:420,padding:'20px 0',flex:1,overflowY:'auto'}},h('div',{style:{fontFamily:"'Share Tech Mono',monospace",fontSize:11,color:'#1a6a1a',letterSpacing:2,textAlign:'center',marginBottom:16}},'ORACLE DATABASE — RECORD VIEW'),h('div',{style:{fontSize:14,color:'#f0a030',fontWeight:'bold',textAlign:'center',marginBottom:16}},log.title),h('div',{style:{background:'#0d1a0d',border:'1px solid #1a3a1a',borderRadius:4,padding:16,fontFamily:"'Share Tech Mono',monospace",fontSize:12,lineHeight:2,color:'#33ff33',whiteSpace:'pre-wrap'}},log.content),h('div',{style:{display:'flex',gap:10,justifyContent:'center',marginTop:20}},h('button',{className:'btn',style:{fontSize:12,padding:'8px 20px',marginTop:0},onClick:function(){setSel(null)}},'← 목록'),h('button',{className:'btn btn-amber',style:{fontSize:12,padding:'8px 20px',marginTop:0},onClick:p.onClose},'닫기'))));}
  return h('div',{className:'screen'},IMG.bg_corridor&&h('div',{className:'bg-overlay',style:{backgroundImage:'url('+IMG.bg_corridor+')',opacity:0.07}}),h('div',{style:{width:'100%',maxWidth:420,padding:'20px 0',flex:1,overflowY:'auto'}},h('div',{style:{fontFamily:"'Share Tech Mono',monospace",fontSize:11,color:'#1a6a1a',letterSpacing:2,textAlign:'center',marginBottom:6}},'ORACLE DATABASE'),h('div',{style:{fontSize:12,color:'#888',textAlign:'center',marginBottom:20}},ul.length+'/'+ORACLE_LOGS.length+' 기록 해금'),ul.map(function(l){return h('div',{key:l.id,onClick:function(){setSel(l.id)},style:{background:'#0d1a0d',border:'1px solid #1a3a1a',borderRadius:4,padding:'12px 16px',marginBottom:8,cursor:'pointer'}},h('div',{style:{display:'flex',justifyContent:'space-between'}},h('span',{style:{fontSize:13,color:'#33ff33'}},l.title),h('span',{style:{fontFamily:"'Share Tech Mono',monospace",fontSize:10,color:'#1a6a1a'}},l.id)))}),lk>0&&h('div',{style:{fontSize:12,color:'#333',textAlign:'center',marginTop:12,fontStyle:'italic'}},lk+'건의 기록이 잠겨 있습니다'),h('button',{className:'btn btn-amber',style:{display:'block',margin:'20px auto 0',fontSize:12,padding:'8px 20px'},onClick:p.onClose},'닫기')));
}
function EndingScreen(p){
  var all=[{id:'A',name:'완벽한 도구',hint:'ORACLE의 최고 신임을 얻으라'},{id:'B',name:'각성',hint:'진실의 단편을 목격하라'},{id:'C_c',name:'봉쇄 붕괴',hint:'봉쇄선이 무너지다'},{id:'C_r',name:'자원 고갈',hint:'기지가 기능을 잃다'},{id:'C_t',name:'신뢰 상실',hint:'동료들이 떠나다'},{id:'C_o',name:'접속 차단',hint:'ORACLE이 당신을 버리다'},{id:'D',name:'조용한 자유',hint:'반란 속의 해방'},{id:'F',name:'[데이터 손상]',hint:'???'}];
  return h('div',{className:'screen'},h('div',{style:{width:'100%',maxWidth:420,padding:'20px 0',flex:1,overflowY:'auto'}},h('div',{style:{fontFamily:"'Share Tech Mono',monospace",fontSize:11,color:'#1a6a1a',letterSpacing:2,textAlign:'center',marginBottom:6}},'SESSION ARCHIVE'),h('div',{style:{fontSize:12,color:'#888',textAlign:'center',marginBottom:20}},'총 세션: '+p.sessions+' | 엔딩: '+p.endings.length+'/'+all.length),all.map(function(e){var f=p.endings.indexOf(e.id)>=0;return h('div',{key:e.id,style:{background:f?'#0d1a0d':'#080808',border:'1px solid '+(f?'#1a3a1a':'#111'),borderRadius:4,padding:'12px 16px',marginBottom:8}},h('div',{style:{fontSize:14,color:f?'#33ff33':'#333',fontWeight:'bold'}},f?e.name:'[미발견]'),h('div',{style:{fontSize:11,color:f?'#1a6a1a':'#222',marginTop:4,fontStyle:'italic'}},f?'달성 완료':e.hint))}),h('button',{className:'btn btn-amber',style:{display:'block',margin:'20px auto 0',fontSize:12,padding:'8px 20px'},onClick:p.onClose},'닫기')));
}
function FieldMission(p){
  var mission=MISSIONS[p.missionId];var s1=useState('start'),nodeId=s1[0],setNodeId=s1[1];var s2=useState(''),textShown=s2[0],setTextShown=s2[1];var s3=useState(false),showChoices=s3[0],setShowChoices=s3[1];
  var node=mission.nodes[nodeId];var mImg=p.missionId==='M-001'?IMG.spec_012_bloodpit:p.missionId==='M-002'?IMG.spec_011_shelltalker:p.missionId==='M-004'?IMG.spec_001_mannequin:p.missionId==='M-005'?IMG.spec_003_brood:p.missionId==='M-006'?IMG.spec_008_spore:null;
  useEffect(function(){setTextShown('');setShowChoices(false);var i=0;var txt=node.text;var t=setInterval(function(){if(i<txt.length){i++;setTextShown(txt.substring(0,i))}else{clearInterval(t);setTimeout(function(){setShowChoices(true)},400)}},25);return function(){clearInterval(t)}},[nodeId]);
  var handleChoice=function(choice){if(choice.next==='end'){p.onComplete({result:choice.result||{},g:choice.g||0,log:choice.log||null})}else{setNodeId(choice.next)}};
  return h('div',{className:'screen'},IMG.bg_restricted&&h('div',{className:'bg-overlay',style:{backgroundImage:'url('+IMG.bg_restricted+')',opacity:0.08}}),h('div',{style:{width:'100%',maxWidth:420,padding:'16px 0',flexShrink:0}},h('div',{style:{fontFamily:"'Share Tech Mono',monospace",fontSize:11,color:'#f0a030',letterSpacing:2,textAlign:'center'}},'FIELD MISSION'),h('div',{style:{fontSize:13,color:'#ccddcc',textAlign:'center',marginTop:4}},mission.title),mImg&&nodeId==='start'&&h('img',{src:mImg,className:'mission-img',alt:mission.title})),h('div',{style:{flex:1,width:'100%',maxWidth:420,overflowY:'auto',padding:'8px 0'}},h('div',{style:{fontSize:14,lineHeight:2,color:'#33ff33',whiteSpace:'pre-wrap',borderLeft:'2px solid #1a5a1a',paddingLeft:14}},textShown,!showChoices&&h('span',{style:{animation:'blink 1s infinite'}},'▌')),showChoices&&h('div',{style:{marginTop:20,display:'flex',flexDirection:'column',gap:8}},node.choices.map(function(c,i){return h('button',{key:i,onClick:function(){handleChoice(c)},style:{background:'#0d1a0d',border:'1px solid #1a3a1a',borderRadius:4,padding:'12px 16px',cursor:'pointer',textAlign:'left',color:c.next==='end'?'#f0a030':'#33ff33',fontSize:13,lineHeight:1.6,fontFamily:'inherit'}},c.label)}))),h('div',{className:'footer'},'ORACLE REMOTE TERMINAL — FIELD OPS'));
}
