// data-cards-6.js — Act 1 일상 카드 (C-113~C-132)

var CARDS_ACT1_DAILY = [
  // ═══ 보급 / 자원 ═══
  { id: "C-113", act: [2], priority: "하", bg: "supply",
    msg: "정기 보급 트럭이 도착했습니다.\n\n물자 목록: 식량 2주분, 의약품, 배터리.",
    left: { label: "의료품 우선 하역", fx: { c: 0, r: 2, t: 1, o: 0 }, g: 0 },
    right: { label: "장비 부품 우선 하역", fx: { c: 1, r: 1, t: 0, o: 1 }, g: 1 } },
  { id: "C-114", act: [2], priority: "하", bg: "supply",
    req: function(s,g,logs){ return !logs.includes("LOG-027") },
    msg: "인근 폐쇄 군부대에서 잔여 물자 발견 보고.\n\n강도윤: \"연료와 방한 장비가 있습니다.\"",
    left: { label: "회수팀 파견", fx: { c: 0, r: 2, t: 0, o: 0 }, g: 0 },
    right: { label: "위험 — 무시", fx: { c: 0, r: 0, t: 0, o: 0 }, g: 0 } },
  { id: "C-115", act: [2], priority: "하", bg: "supply",
    msg: "임재혁이 태양광 패널 설치를 제안합니다.\n\n\"전력 자급률을 높일 수 있습니다.\"",
    left: { label: "설치 승인", fx: { c: 0, r: -1, t: 0, o: 1 }, g: 1 },
    right: { label: "현 발전기로 충분", fx: { c: 0, r: 0, t: 0, o: -1 }, g: 0 } },
  { id: "C-116", act: [2], priority: "하", bg: "supply",
    msg: "ORACLE 보급 스케줄 갱신.\n\n[ORACLE: 다음 보급까지 8일. 현 소비율 유지 시 3일 여유.]",
    left: { label: "배급량 줄여 비축", fx: { c: 0, r: 2, t: -1, o: 1 }, g: 1 },
    right: { label: "현 배급 유지", fx: { c: 0, r: 0, t: 1, o: 0 }, g: 0 } },

  // ═══ 인사 / 사기 ═══
  { id: "C-117", act: [2], priority: "하", bg: "base",
    msg: "야간 근무조가 휴식 시간 연장을 요청했습니다.\n\n현재 6시간 수면. 8시간을 원합니다.",
    left: { label: "8시간 수면 허용", fx: { c: -1, r: 0, t: 2, o: 0 }, g: 0 },
    right: { label: "6시간 유지 — 경계 우선", fx: { c: 1, r: 0, t: -1, o: 1 }, g: 1 } },
  { id: "C-118", act: [2], priority: "하", bg: "base",
    msg: "요원 생일. 소규모 축하가 가능합니다.\n\n\"보급품 중 초콜릿이 있습니다.\"",
    left: { label: "축하 파티 허용", fx: { c: 0, r: -1, t: 2, o: 0 }, g: 0 },
    right: { label: "평소대로 근무", fx: { c: 0, r: 0, t: -1, o: 0 }, g: 0 } },
  { id: "C-119", act: [2], priority: "하", bg: "base",
    msg: "신규 배치 요원이 적응에 어려움을 겪고 있습니다.\n\n강도윤: \"제가 맡겠습니다.\"",
    left: { label: "강도윤에게 맡긴다", fx: { c: 0, r: 0, t: 1, o: 0 }, g: 0 },
    right: { label: "직접 면담한다", fx: { c: 0, r: 0, t: 2, o: 0 }, g: -1 } },

  // ═══ 시설 / 정비 ═══
  { id: "C-120", act: [2], priority: "하", bg: "base",
    msg: "기지 환기 시스템에서 이상음이 발생합니다. 낮은 진동이 복도까지 울립니다.\n\n임재혁: \"팬 베어링이 나갔습니다. 교체하면 반나절인데, 그동안 환기가 멈춥니다. 안 고치면 소음은 계속되고 결국 모터가 타요.\"",
    left: { label: "즉시 수리", fx: { c: 0, r: -1, t: 1, o: 0 }, g: 0 },
    right: { label: "다음 주에", fx: { c: 0, r: 0, t: -1, o: 0 }, g: 0 } },
  { id: "C-121", act: [2], priority: "하", bg: "base",
    msg: "기지 외벽에 균열 발견.\n\n\"구조적 문제는 아니지만 방수 처리가 필요합니다.\"",
    left: { label: "보수 작업 실시", fx: { c: 1, r: -1, t: 0, o: 0 }, g: 0 },
    right: { label: "모니터링만", fx: { c: 0, r: 0, t: 0, o: 0 }, g: 0 } },
  { id: "C-122", act: [2], priority: "하", bg: "lab",
    msg: "윤세진이 연구 장비 업그레이드를 요청합니다.\n\n\"현미경 해상도가 부족합니다.\"",
    left: { label: "예산 배정", fx: { c: 0, r: -2, t: 1, o: 0 }, g: 0 },
    right: { label: "기존 장비로 대응", fx: { c: 0, r: 0, t: -1, o: 0 }, g: 0 } },

  // ═══ 순찰 / 봉쇄 ═══
  { id: "C-123", act: [2], priority: "하", bg: "forest",
    msg: "봉쇄선 동쪽 구간 센서가 노후화되었습니다.\n\n강도윤: \"교체하면 탐지 범위가 30% 넓어집니다.\"",
    left: { label: "센서 교체", fx: { c: 2, r: -1, t: 0, o: 1 }, g: 1 },
    right: { label: "수동 순찰로 보완", fx: { c: 1, r: 0, t: 0, o: 0 }, g: 0 } },
  { id: "C-124", act: [2], priority: "하", bg: "forest",
    req: function(s,g,logs){ return !logs.includes("LOG-028") },
    msg: "순찰 중 야생 동물 사체 발견.\n\nEV-Σ 감염 여부 불명.\n\n윤세진: \"샘플 채취하면 확인 가능합니다.\"",
    left: { label: "샘플 채취", fx: { c: 1, r: -1, t: 0, o: 1 }, g: 1 },
    right: { label: "소각 처리", fx: { c: 1, r: 0, t: 0, o: 0 }, g: 0 } },
  { id: "C-125", act: [2], priority: "하", bg: "forest",
    msg: "봉쇄선 인근에서 캠핑 흔적이 발견되었습니다.\n\n민간인으로 추정.\n\n강도윤: \"최소 2명. 1~2일 전.\"",
    left: { label: "추적 조사", fx: { c: 1, r: -1, t: 0, o: 0 }, g: -1 },
    right: { label: "경고 표지판 설치", fx: { c: 0, r: 0, t: 0, o: 1 }, g: 1 } },

  // ═══ 날씨 / 환경 ═══
  { id: "C-126", act: [2], priority: "하", bg: "weather", tag: "weather",
    msg: "기상 예보: 내일 폭설.\n\n외부 활동이 제한됩니다.",
    left: { label: "방한 장비 점검", fx: { c: 0, r: -1, t: 1, o: 0 }, g: 0 },
    right: { label: "평소대로 대비", fx: { c: 0, r: 0, t: 0, o: 0 }, g: 0 } },
  { id: "C-127", act: [2], priority: "하", bg: "weather", tag: "weather",
    msg: "밤새 안개가 짙습니다.\n\n봉쇄선 가시거리 50m 미만.\n\n강도윤: \"순찰 효율이 절반입니다.\"",
    left: { label: "열감지 장비 투입", fx: { c: 1, r: -1, t: 0, o: 1 }, g: 1 },
    right: { label: "안개 해소까지 대기", fx: { c: -1, r: 0, t: 0, o: 0 }, g: 0 } },

  // ═══ 통신 / ORACLE ═══
  { id: "C-128", act: [2], priority: "하", bg: "comms",
    msg: "[ORACLE: 정기 데이터 동기화 예정.]\n\n4시간 동안 처리 속도가 저하됩니다.",
    left: { label: "야간에 진행", fx: { c: 0, r: 0, t: 0, o: 1 }, g: 1 },
    right: { label: "즉시 진행", fx: { c: 0, r: 0, t: 0, o: 0 }, g: 0 } },
  { id: "C-129", act: [2], priority: "하", bg: "comms",
    msg: "타 지부에서 봉쇄 운영 데이터 공유를 요청합니다.\n\n[ORACLE: 공유를 권장합니다.]",
    left: { label: "데이터 공유", fx: { c: 0, r: 0, t: 0, o: 2 }, g: 2 },
    right: { label: "보안상 거절", fx: { c: 0, r: 0, t: 0, o: -1 }, g: -1 } },

  // ═══ 훈련 / 대비 ═══
  { id: "C-130", act: [2], priority: "하", bg: "base",
    msg: "강도윤이 요원 대상 근접전 훈련을 제안합니다.\n\n\"이변체와 마주치면 사격만으론 안 됩니다.\"",
    left: { label: "훈련 실시", fx: { c: 1, r: 0, t: 1, o: 0 }, g: 0 },
    right: { label: "사격 훈련이 우선", fx: { c: 1, r: -1, t: 0, o: 1 }, g: 1 } },
  { id: "C-131", act: [2], priority: "하", bg: "lab",
    msg: "윤세진이 기지 내 간이 격리 시설 구축을 요청합니다.\n\n\"감염 의심 사례 발생 시 즉시 대응이 가능해집니다.\"",
    left: { label: "격리실 구축", fx: { c: 1, r: -2, t: 0, o: 1 }, g: 1, fePropose: "FE-004" },
    right: { label: "의무실 격리로 충분", fx: { c: 0, r: 0, t: 0, o: 0 }, g: 0 } },
  { id: "C-132", act: [2], priority: "하", bg: "base",
    msg: "기지 비상 발전기 정기 점검일입니다.\n\n임재혁: \"30분이면 끝납니다. 다만 그동안 기지 전체가 정전이에요. 야간에 할지 주간에 할지, 지휘관님이 정해주십시오.\"",
    left: { label: "주간에 점검", fx: { c: -1, r: 0, t: 1, o: 1 }, g: 1 },
    right: { label: "야간에 점검", fx: { c: 1, r: 0, t: -1, o: 0 }, g: 0 } },

  // ═══ 후속 카드 ═══
  { id: "C-155", act: [2,3], priority: "하", bg: "supply",
    req: function(s,g,logs){ return logs.includes("LOG-027") && s.day >= 5 },
    msg: "이전에 발견한 군부대 잔여 구역을 재탐색했습니다.\n\n\"탄약고는 비었지만 의약품 저장고가 남아 있습니다.\"",
    left: { label: "회수 진행", fx: { c: 0, r: 2, t: 0, o: 0 }, g: 0 },
    right: { label: "부비트랩 위험 — 포기", fx: { c: 0, r: 0, t: 1, o: 0 }, g: 0 } },
  { id: "C-156", act: [2,3], priority: "하", bg: "forest",
    req: function(s,g,logs){ return logs.includes("LOG-028") && s.day >= 6 },
    msg: "이전 사체 발견 지점 인근 모니터링 결과.\n\n윤세진: \"추가 감염 징후 없음. 격리 지역 아닙니다.\"",
    left: { label: "순찰 구역에 포함", fx: { c: 1, r: 0, t: 0, o: 0 }, g: 0 },
    right: { label: "관찰만 유지", fx: { c: 0, r: 0, t: 0, o: 0 }, g: 0 } }
];
