// TERMINAL SESSION — images.js
const IMG = {
  bg_seoul_a: "assets/images/backgrounds/bg_seoul_a.jpg",
  bg_seoul_b: "assets/images/backgrounds/bg_seoul_b.jpg",
  char_doyun: "assets/images/characters/char_doyun.jpg",
  char_foster: "assets/images/characters/char_foster.jpg",
  char_haeun_tense: "assets/images/characters/char_haeun_tense.jpg",
  char_haeun: "assets/images/characters/char_haeun.jpg",
  char_jaehyuk_sad: "assets/images/characters/char_jaehyuk_sad.jpg",
  char_jaehyuk: "assets/images/characters/char_jaehyuk.jpg",
  char_jungchul: "assets/images/characters/char_jungchul.jpg",
  char_sejin: "assets/images/characters/char_sejin.jpg",
  char_soyoung_shadow: "assets/images/characters/char_soyoung_shadow.jpg",
  char_soyoung: "assets/images/characters/char_soyoung.jpg",
  char_weber: "assets/images/characters/char_weber.jpg",
  spec_011_shelltalker: "assets/images/specs/spec_011_shelltalker.jpg",
  spec_012_bloodpit: "assets/images/specs/spec_012_bloodpit.jpg",
  spec_004_seedspreader: "assets/images/specs/spec_004_seedspreader.jpg",
  spec_015_brainseeker: "assets/images/specs/spec_015_brainseeker.jpg",
  bg_command: "assets/images/backgrounds/bg_command.jpg",
  bg_corridor: "assets/images/backgrounds/bg_corridor.jpg",
  title_screen: "assets/images/backgrounds/title_screen.jpg",
  bg_restricted: "assets/images/backgrounds/bg_restricted.jpg",
  spec_001_mannequin: "assets/images/specs/spec_001_mannequin.jpg",
  spec_003_brood: "assets/images/specs/spec_003_brood.jpg",
  spec_008_spore: "assets/images/specs/spec_008_spore.jpg",
  ending_A: "ending_A.png",
  ending_B: "ending_B.png",
  ending_C_c: "ending_C_c.png",
  ending_C_cs: "ending_C_cs.png",
  ending_C_cst: "ending_C_cs.png",
  ending_C_o: "ending_C_o.png",
  ending_C_r: "ending_C_r.png",
  ending_C_t: "ending_C_t.png",
  ending_D: "ending_D.png",
  ending_E: "ending_E.png",
  ending_E_bad: "ending_E_bad.png",
  ending_E_c: "ending_E_c.png",
  ending_F: "ending_F.png",
  ending_G: "ending_G.png",
  ending_H: "ending_H.png",
};

const CHAR_IMG = {
  "이중철": IMG.char_jungchul,
  "서하은": IMG.char_haeun,
  "서하은_긴장": IMG.char_haeun_tense,
  "강도윤": IMG.char_doyun,
  "윤세진": IMG.char_sejin,
  "임재혁": IMG.char_jaehyuk,
  "임재혁_실망": IMG.char_jaehyuk_sad,
  "마르쿠스 베버": IMG.char_weber,
  "닉 포스터": IMG.char_foster,
  "박소영": IMG.char_soyoung,
  "박소영_그림자": IMG.char_soyoung_shadow,
};
