// data-cards-1.js — 기본 카드 (C-001~C-051)
var CARDS_BASE = [
  { id: "C-001", act: [1,2,3], priority: "하", msg: "신규 요원 3명이 기지에 도착했습니다. 배치 승인이 필요합니다.", left: { label: "내일 배치", fx: { c: 0, r: 0, t: -1, o: -1 }, g: -1 }, right: { label: "즉시 배치", fx: { c: 1, r: -1, t: 1, o: 1 }, g: 1 } },
  { id: "C-002", act: [1,2,3], priority: "중", msg: "봉쇄 구역 외곽에서 민간인 접근 시도 감지. 대응 지침을 결정하십시오.", left: { label: "경고 방송만", fx: { c: -1, r: 0, t: 1, o: -1 }, g: -1 }, right: { label: "요원 파견 차단", fx: { c: 1, r: -1, t: -1, o: 1 }, g: 1 } },
  { id: "C-003", act: [1], priority: "상", tag: "spec-011", req: function(s,g,logs){ return !logs.includes("LOG-004") }, msg: "인접 셀 C-14에서 SPEC-011 (Shell Talker) 목격 보고.\n\n\"인간의 목소리로 구조 요청을 흉내냅니다. 접근한 요원 1명이 유인당했습니다.\"\n\n해당 셀 요원이 지원 요청.", left: { label: "거절: 자원 보존", fx: { c: 0, r: 0, t: -1, o: -1 }, g: -1 }, right: { label: "요원 2명 파견", fx: { c: -1, r: 0, t: 1, o: 1 }, g: 1 } },
  { id: "C-004", act: [1,2,3], priority: "하", msg: "의무실에서 의료 물자 부족 보고. 외부 조달 요청이 올라왔습니다.", left: { label: "내부 재고로 버텨", fx: { c: 0, r: -1, t: -1, o: 0 }, g: -1 }, right: { label: "외부 조달 승인", fx: { c: 0, r: 2, t: 0, o: -1 }, g: 1 } },
  { id: "C-005", act: [1], priority: "하", msg: "임재혁 기술관이 ORACLE 단말기 펌웨어 업데이트를 제안합니다.", left: { label: "보류", fx: { c: 0, r: 0, t: 0, o: -1 }, g: -1 }, right: { label: "업데이트 승인", fx: { c: 0, r: -1, t: 0, o: 2 }, g: 2 } },
  { id: "C-006", act: [1,2], priority: "상", msg: "서울 동부 봉쇄 구역 인근에서 프로메테우스 소속 추정 인원 3명 활동 감지.", left: { label: "감시만: 정보 수집", fx: { c: 0, r: 0, t: 0, o: -2 }, g: -2 }, right: { label: "즉각 대응팀 투입", fx: { c: 1, r: -2, t: 1, o: 2 }, g: 2 } },
  { id: "C-007", act: [1], priority: "중", msg: "강도윤 요원이 봉쇄선 외곽 정찰을 자원합니다. 단독 작전입니다.", left: { label: "허가", fx: { c: 1, r: 0, t: 1, o: -1 }, g: -1 }, right: { label: "ORACLE 판단 요청", fx: { c: 0, r: 0, t: 0, o: 1 }, g: 2 } },
  { id: "C-008", act: [1,2], priority: "중", msg: "서하은 부지휘관 보고: ORACLE 데이터 스트림에서 미세한 불일치 패턴 발견.", left: { label: "독자 조사 허가", fx: { c: 0, r: 0, t: 1, o: -2 }, g: -3 }, right: { label: "ORACLE에 분석 위임", fx: { c: 0, r: 0, t: -1, o: 2 }, g: 2 } },
  { id: "C-009", act: [1,2,3], priority: "하", msg: "기지 인원 사기 저하 보고. 휴식 시간 확대 요청.", left: { label: "현행 유지", fx: { c: 0, r: 0, t: -2, o: 1 }, g: 0 }, right: { label: "휴식 확대 승인", fx: { c: -1, r: 0, t: 2, o: -1 }, g: 0 } },
  { id: "C-010", act: [1], priority: "상", tag: "spec-012", req: function(s,g,logs){ return !logs.includes("LOG-005") }, msg: "봉쇄 구역 내 SPEC-012 (Blood Pit) 활동 징후 감지. 붉은 점액질 웅덩이가 확장 중입니다.\n\n강도윤: \"밟는 순간 꼼짝 못 합니다. 벌레잡이 식물 같은 겁니다.\"", left: { label: "구역 격리만", fx: { c: -1, r: 0, t: 0, o: -1 }, g: -1 }, right: { label: "표본 원격 채취", fx: { c: 0, r: 0, t: 0, o: 1 }, g: 1 } },
  { id: "C-011", act: [1,2], priority: "중", img: "card_signal_overlap", msg: "미확인 무선 신호 수신. 프로메테우스 암호 패턴과 유사합니다.", left: { label: "신호 추적", fx: { c: 0, r: -1, t: 0, o: -1 }, g: -2 }, right: { label: "ORACLE 분석 의뢰", fx: { c: 0, r: 0, t: 0, o: 1 }, g: 2 } },
  { id: "C-012", act: [1,2,3], priority: "하", msg: "강원도 내 민간 뉴스 — '야간 군사 차량 이동' 목격담 확산. 기지 보안 위험.", left: { label: "무시", fx: { c: 0, r: 0, t: 0, o: 0 }, g: 0 }, right: { label: "이동 경로 변경", fx: { c: 0, r: -1, t: 1, o: 1 }, g: 1 } },
  { id: "C-013", act: [1,2], priority: "상", msg: "ORACLE 긴급 통신: 봉쇄 구역 남측 경계에서 다수 생체 반응 감지. 즉각 대응 필요.", left: { label: "기지 방어 강화", fx: { c: -1, r: 0, t: 1, o: -1 }, g: -1 }, right: { label: "선제 출격", fx: { c: 2, r: -2, t: 0, o: 2 }, g: 1 } },
  { id: "C-014", act: [1], priority: "중", msg: "윤세진 연구원이 이변체 관찰 기록을 개인적으로 작성하고 있습니다. 보안 위반 여부 판단 필요.", left: { label: "묵인", fx: { c: 0, r: 0, t: 1, o: -2 }, g: -3 }, right: { label: "기록 압수 + 경고", fx: { c: 0, r: 0, t: -1, o: 2 }, g: 2 } },
  { id: "C-015", act: [1,2], priority: "중", msg: "ORACLE 권고: 기지 운영 효율 향상을 위해 의사결정 프로토콜을 ORACLE 자동화로 전환할 것을 제안합니다.", left: { label: "거절: 수동 유지", fx: { c: 0, r: 0, t: 1, o: -3 }, g: -4 }, right: { label: "부분 자동화 승인", fx: { c: 1, r: 1, t: -1, o: 3 }, g: 4 } },
  // 조건부 카드
  { id: "C-016", act: [1,2], priority: "상", req: (s, g) => s.day >= 3 && g <= 40, msg: "[미분류 통신] ORACLE 데이터 링크 일시적 불안정. 미확인 암호화 통신(소바리 발신 추정)이 수신되었습니다.", left: { label: "무시 (권장)", fx: { c: 0, r: 0, t: 0, o: 1 }, g: 2 }, right: { label: "독자 해독 시도", fx: { c: 0, r: 0, t: 1, o: -2 }, g: -3 } },
  { id: "C-017", act: [2], priority: "중", req: (s, g, logs) => logs.includes("LOG-003"), msg: "이전 수집된 프로메테우스 통신 패턴을 기반으로 인근의 은신처를 특정했습니다.", left: { label: "ORACLE 보고", fx: { c: 1, r: 0, t: 0, o: 2 }, g: 3 }, right: { label: "비공식 접촉", fx: { c: -1, r: 0, t: 2, o: -2 }, g: -4 } },
  { id: "C-018", act: [2], priority: "상", req: (s) => s.day >= 5 && s.c < 40, msg: "봉쇄 구역 경계에서 대규모 이변체 이동 징후 포착. 현재 봉쇄력으로는 대응이 불확실합니다.", left: { label: "전 요원 방어 배치", fx: { c: 2, r: -2, t: 1, o: 0 }, g: 0 }, right: { label: "ORACLE에 지원 요청", fx: { c: 1, r: -1, t: -1, o: 2 }, g: 3 } },
  { id: "C-019", act: [2], priority: "중", req: (s, g, logs) => logs.includes("LOG-008"), msg: "강도윤이 보고한 '미분류 활동 흔적'과 동일한 패턴이 기지 인근에서 재탐지되었습니다.", left: { label: "경계 태세 강화", fx: { c: 1, r: -1, t: 0, o: 0 }, g: 0 }, right: { label: "단독 추적", fx: { c: 0, r: -1, t: 1, o: -1 }, g: -2, mission: "M-003" } },
  { id: "C-020", act: [2,3], priority: "하", img: "card_oracle_error", req: (s, g) => g <= 20, msg: "[통신 오류] ORA..LE 시스... 일시적 ████. 다음 메시지를 수신했습니다: '당신은 관측되고 있습니다.'", left: { label: "ORACLE에 오류 보고", fx: { c: 0, r: 0, t: 0, o: 1 }, g: 2 }, right: { label: "...가만히 있는다", fx: { c: 0, r: 0, t: 0, o: -1 }, g: -5 } },
  { id: "C-021", act: [2,3], priority: "중", req: (s, g, logs) => s.day >= 7 && logs.includes("LOG-006"), msg: "서하은 부지휘관이 긴급 면담을 요청합니다. 표정이 심각합니다.", left: { label: "즉시 면담", fx: { c: 0, r: 0, t: 2, o: -1 }, g: -2 }, right: { label: "내일로 미루기", fx: { c: 0, r: 0, t: -1, o: 0 }, g: 0 } },
  { id: "C-022", act: [3], priority: "상", req: (s, g) => s.day >= 10 && g >= 50, msg: "ORACLE 특별 통신: 지휘관의 탁월한 운영 성과를 인정합니다. 권한 확대를 제안합니다.", left: { label: "수락", fx: { c: 1, r: 1, t: -1, o: 3 }, g: 5 }, right: { label: "현행 유지", fx: { c: 0, r: 0, t: 1, o: -2 }, g: -3 } },
  // ── 추가 카드: 일상 운영 ──
  { id: "C-023", act: [1,2,3], priority: "하", img: "card_water_contaminate", msg: "기지 식수 정화 시설에 이상이 감지되었습니다. 수질 검사 결과 오염도가 기준치의 3배입니다.", left: { label: "응급 수리", fx: { c: 0, r: -1, t: 1, o: 0 }, g: 0 }, right: { label: "ORACLE 최적 해법 문의", fx: { c: 0, r: -1, t: 0, o: 1 }, g: 2 } },
  { id: "C-024", act: [1,2,3], priority: "하", msg: "야간 근무 요원 2명 사이에서 언쟁이 발생했습니다. 한 명이 교대 거부를 선언했습니다.", left: { label: "직접 중재", fx: { c: 0, r: 0, t: 2, o: -1 }, g: -1 }, right: { label: "강도윤에게 처리 위임", fx: { c: 0, r: 0, t: 1, o: 0 }, g: 0 } },
  { id: "C-025", act: [1,2,3], priority: "중", tag: "weather", img: "card_flood", msg: "폭우로 인해 외부 보급로가 48시간 이상 차단될 전망입니다. 비상 물자 배분이 필요합니다.", left: { label: "배급제 시행", fx: { c: 0, r: 1, t: -1, o: 0 }, g: 0 }, right: { label: "대체 경로 탐색 (위험)", fx: { c: -1, r: 0, t: 0, o: 0 }, g: 0 } },
  { id: "C-026", act: [1], priority: "중", msg: "기지 보안 점검 중 CCTV 사각지대 3곳이 발견되었습니다. 임재혁이 즉시 보완을 건의합니다.", left: { label: "즉시 보완", fx: { c: 1, r: -1, t: 0, o: 0 }, g: 0 }, right: { label: "ORACLE 감시 시스템으로 대체", fx: { c: 1, r: 0, t: -1, o: 1 }, g: 2 } },
  { id: "C-027", act: [1,2,3], priority: "하", msg: "기지 인원의 평균 수면 시간이 4.2시간으로 떨어졌습니다. 윤세진이 건강 악화를 경고합니다.", left: { label: "순환 휴가 편성", fx: { c: -1, r: 0, t: 2, o: 0 }, g: 0 }, right: { label: "현 상태 유지 (작전 우선)", fx: { c: 0, r: 0, t: -2, o: 1 }, g: 1 } },
  // ── 추가 카드: 이변체 (태그 + 텍스트 변형) ──
  { id: "C-028", act: [1,2], priority: "중", tag: "spec-011", img: "card_shelltalker_lure", msg: "봉쇄선 북측 감시 장비에서 인간 음성 패턴이 감지되었습니다.\n\n음성 분석 결과: SPEC-011 (Shell Talker) 활동으로 추정.\n\n해당 음성은 3개월 전 실종된 인접 셀 요원의 것입니다.", left: { label: "기록만 남기고 경계", fx: { c: 0, r: 0, t: 0, o: 0 }, g: 0 }, right: { label: "음성 데이터 수집팀 파견", fx: { c: 0, r: -1, t: 0, o: 1 }, g: 1 } },
  { id: "C-029", act: [1,2], priority: "중", tag: "spec-012", msg: "봉쇄 구역 동측 건물 지하에서 적갈색 액체 웅덩이가 다수 확인되었습니다.\n\nORACLE 분석: SPEC-012 (Blood Pit). 변이 실패체의 용해 잔해.\n\n밟으면 고착됩니다. 이동 경로 재설정이 필요합니다.", left: { label: "지하 경로 폐쇄", fx: { c: -1, r: 0, t: 1, o: 0 }, g: 0 }, right: { label: "표시 후 우회 경로 설정", fx: { c: 0, r: -1, t: 0, o: 1 }, g: 1 } },
  { id: "C-030", act: [1,2], priority: "상", req: (s) => s.day >= 4, msg: "강도윤 긴급 보고: 봉쇄 구역 내에서 기존 분류에 없는 생체 반응 감지.\n\n\"기존 이변체와 패턴이 다릅니다. 새로운 종일 수 있습니다.\"\n\n[ORACLE: 데이터 불충분. 분류 보류.]", left: { label: "원거리 관측만 실시", fx: { c: 0, r: 0, t: 1, o: 0 }, g: 0 }, right: { label: "접근 조사팀 편성", fx: { c: 1, r: -2, t: 0, o: 1 }, g: 1 } },
  { id: "C-031", act: [1,2], priority: "중", tag: "spec-011", req: (s) => s.day >= 6, msg: "윤세진 보고: 이변체 행동 패턴에 계절적 변화가 관측됩니다.\n\n\"Shell Talker의 활동 반경이 지난주 대비 40% 확대되었습니다.\"\n\n\"이건 단순한 이동이 아니에요. 뭔가를 찾고 있는 것처럼 보입니다.\"", left: { label: "윤세진 연구 지원", fx: { c: 0, r: -1, t: 1, o: -1 }, g: -1 }, right: { label: "ORACLE에 패턴 분석 의뢰", fx: { c: 0, r: 0, t: 0, o: 1 }, g: 2 } },
  // ── 추가 카드: 프로메테우스 ──
  { id: "C-032", act: [1,2], priority: "중", req: (s) => s.day >= 3, msg: "임재혁 보고: 프로메테우스가 사용하던 무선 주파수가 변경되었습니다.\n\n\"이전 주파수에 미끼 신호를 남겨뒀습니다. 우리가 감청하고 있다는 걸 알고 있을 수 있습니다.\"", left: { label: "새 주파수 추적", fx: { c: 0, r: -1, t: 0, o: -1 }, g: -2 }, right: { label: "ORACLE에 역추적 요청", fx: { c: 0, r: 0, t: 0, o: 1 }, g: 2 } },
  { id: "C-033", act: [1,2], priority: "중", req: (s) => s.day >= 5, msg: "기지 외곽 300m 지점에서 버려진 장비가 발견되었습니다.\n\n분석 결과: 프로메테우스 규격 야간 투시경. 최근 제조.\n\n누군가 이곳을 감시하고 있었습니다.", left: { label: "장비를 미끼로 역감시", fx: { c: 0, r: -1, t: 0, o: -1 }, g: -2 }, right: { label: "ORACLE에 보고 + 장비 전송", fx: { c: 0, r: 0, t: 0, o: 2 }, g: 3 } },
  { id: "C-034", act: [2], priority: "상", req: (s, g, logs) => s.day >= 8 && logs.includes("LOG-003") && g <= 35, msg: "기지 통신 채널에 미확인 메시지가 수신되었습니다.\n\n\"우리는 적이 아닙니다. 대화할 의향이 있다면, 내일 밤 북측 500m 지점.\"\n\n발신자 불명. 프로메테우스 암호 패턴과 70% 일치.", left: { label: "무시한다", fx: { c: 0, r: 0, t: 0, o: 1 }, g: 2 }, right: { label: "접선에 응한다", fx: { c: -1, r: 0, t: 1, o: -3 }, g: -5 } },
  // ── 추가 카드: ORACLE ──
  { id: "C-035", act: [2], priority: "하", msg: "ORACLE이 기지 운영 데이터의 외부 백업을 요청합니다.\n\n[ORACLE: 데이터 무결성 보장을 위해 전체 로그를 본부 서버로 전송합니다.]\n\n서하은: \"전체 로그라면... 우리의 내부 통신 기록도 포함됩니다.\"", left: { label: "내부 통신은 제외", fx: { c: 0, r: 0, t: 1, o: -2 }, g: -3 }, right: { label: "전체 백업 승인", fx: { c: 0, r: 0, t: -1, o: 2 }, g: 3 } },
  { id: "C-036", act: [2], priority: "중", req: (s) => s.day >= 4, msg: "ORACLE이 전 요원 대상 심리 적합성 평가를 제안합니다.\n\n[ORACLE: 장기 운영 효율 최적화를 위해 인원 재배치가 필요할 수 있습니다.]\n\n강도윤: \"심리 평가라... 부적합 판정 나면 누가 빠지는 겁니까?\"", left: { label: "거절한다", fx: { c: 0, r: 0, t: 2, o: -2 }, g: -3 }, right: { label: "형식적으로 실시", fx: { c: 0, r: 0, t: -1, o: 2 }, g: 2 } },
  { id: "C-037", act: [2], priority: "중", req: (s) => s.day >= 6, msg: "임재혁 보고: ORACLE 시스템이 승인 없이 자동 업그레이드를 실행했습니다.\n\n\"변경 로그를 확인했는데... 일부 모듈이 '접근 불가'로 변경되어 있습니다.\"\n\n\"제가 관리자인데 접근이 안 됩니다.\"", left: { label: "해당 모듈 접근 시도", fx: { c: 0, r: 0, t: 1, o: -2 }, g: -4 }, right: { label: "ORACLE에 해명 요청", fx: { c: 0, r: 0, t: 0, o: 1 }, g: 1 } },
  // ── 추가 카드: 외부 세계 (잠금 — 스토리 미확정) ──
  { id: "C-038", priority: "중", req: () => false, msg: "[잠금]", left: { label: "-", fx: {} }, right: { label: "-", fx: {} } },
  { id: "C-039", priority: "하", req: () => false, msg: "[잠금]", left: { label: "-", fx: {} }, right: { label: "-", fx: {} } },
  // ── 추가 카드: 인물 ──
  { id: "C-040", act: [1,2], priority: "중", req: (s) => s.day >= 5, msg: "임재혁이 3일째 야근 중입니다. ORACLE 시스템 로그를 역추적하고 있는 것 같습니다.\n\n\"지휘관님, 아직 확실하진 않지만... 흥미로운 걸 발견했습니다.\"\n\n그의 눈 밑에 짙은 그림자가 보입니다.", left: { label: "쉬어라. 내일 보고해", fx: { c: 0, r: 0, t: 1, o: 0 }, g: 0 }, right: { label: "지금 보고해", fx: { c: 0, r: 0, t: 0, o: -1 }, g: -1 } },
  { id: "C-041", act: [1], priority: "중", req: (s) => s.day >= 4, msg: "강도윤이 외곽 순찰 중 발목을 다쳤습니다. 윤세진 진단: 경미한 염좌.\n\n강도윤: \"이 정도로 빠질 수는 없습니다.\"\n\n윤세진: \"최소 3일은 현장 복귀를 제한해야 합니다.\"", left: { label: "윤세진 의견 따르기", fx: { c: -1, r: 0, t: 1, o: 0 }, g: 0 }, right: { label: "강도윤 판단에 맡기기", fx: { c: 0, r: 0, t: 0, o: 0 }, g: 0 } },
  // ── SPEC-001 감염체 마네킹 ──
  { id: "C-042", act: [2], priority: "상", tag: "spec-001", req: function(s,g,logs){ return !logs.includes("LOG-013") }, msg: "봉쇄 구역 내 상가 건물 정찰 중, 2층 창문 쪽에 인간 형태가 서 있는 것이 관측되었습니다.\n\n완전히 정지 상태. 호흡 감지 불가. 피부에 비정상적 광택.\n\n[ORACLE: SPEC-001 (감염체 마네킹) 추정. EV-Σ Phase 1. 접촉 금지.]", left: { label: "3m 밖에서 관측만", fx: { c: 0, r: 0, t: 1, o: 0 }, g: 0 }, right: { label: "열감지 스캐너로 확인", fx: { c: 1, r: -1, t: 0, o: 1 }, g: 1 } },
  { id: "C-043", act: [2], priority: "상", tag: "spec-001", req: (s) => s.day >= 5, msg: "긴급 보고 — 정찰조가 건물 내부에서 SPEC-001과 접촉 사고.\n\n\"마네킹인 줄 알았습니다. 장비 회수하려고 손을 뻗는 순간 — 0.3초 만에 목을 잡혔습니다.\"\n\n요원 1명 경상. 즉시 후퇴 완료.\n\n[ORACLE: 해당 건물 전체를 격리 구역으로 재지정합니다.]", left: { label: "건물 봉쇄 + 접근 금지", fx: { c: 1, r: -1, t: 1, o: 0 }, g: 0 }, right: { label: "ORACLE 원격 감시 설치", fx: { c: 1, r: -1, t: 0, o: 1 }, g: 2 } },
  // ── SPEC-003 Brood Drone ──
  { id: "C-044", act: [2], priority: "상", tag: "spec-003", req: function(s,g,logs){ return !logs.includes("LOG-014") }, msg: "봉쇄선 남측에서 소형 개체 다수가 이동 중입니다.\n\n강도윤: \"크기는 사람의 절반 정도. 외골격. 단안. 최소 20체가 편대 이동 중입니다.\"\n\n[ORACLE: SPEC-003 (Brood Drone) 확인. 하나는 약합니다. 문제는 하나인 적이 없다는 것입니다.]", left: { label: "봉쇄선 방어 태세", fx: { c: 1, r: -1, t: 0, o: 0 }, g: 0 }, right: { label: "군체 통신 교란 장비 가동", fx: { c: 2, r: -2, t: 0, o: 1 }, g: 1 } },
  { id: "C-045", act: [2], priority: "상", tag: "spec-003", req: (s) => s.day >= 6, msg: "Brood Drone 집단이 기지 외곽 500m까지 접근했습니다.\n\n약 40체. 이전보다 조직적입니다. 대형을 갖추고 있습니다.\n\n강도윤: \"누군가가 이것들을 지휘하고 있습니다. 드론끼리는 이런 전술을 못 합니다.\"\n\n[ORACLE: 상위 지휘 개체 존재 가능성. 경계 강화 권고.]", left: { label: "방어선 후퇴 + 집결", fx: { c: -1, r: 0, t: 1, o: 0 }, g: 0 }, right: { label: "지휘 개체 색출 작전", fx: { c: 1, r: -2, t: 0, o: 1 }, g: 1 } },
  // ── SPEC-008 Spore Phantom ──
  { id: "C-046", act: [2], priority: "중", tag: "spec-008", req: function(s,g,logs){ return !logs.includes("LOG-015") }, msg: "봉쇄 구역 내 안개가 비정상적으로 짙어지고 있습니다.\n\n정찰조 보고: \"안개 속에서 사람처럼 걸어오는 형체가 보입니다. 조명을 비추면 흩어졌다가 — 더 가까이에서 다시 나타납니다.\"\n\n[ORACLE: SPEC-008 (Spore Phantom) 추정. 포자 집합체. 실체 불명. 흡입 위험.]", left: { label: "정찰조 즉시 철수", fx: { c: -1, r: 0, t: 1, o: 0 }, g: 0 }, right: { label: "방독면 착용 후 관측", fx: { c: 0, r: -1, t: 0, o: 1 }, g: 1 } },
  { id: "C-047", act: [2], priority: "중", tag: "spec-008", req: (s) => s.day >= 7, msg: "윤세진 긴급 보고: 기지 인근 포자 농도가 기준치의 5배를 초과했습니다.\n\n\"Spore Phantom이 접근하고 있는 것 같습니다. 환기 시스템을 밀폐 모드로 전환해야 합니다.\"\n\n[ORACLE: 포자 흡입 시 즉시 감염. 외부 활동 제한 권고.]", left: { label: "기지 밀폐 + 외부 활동 중단", fx: { c: -2, r: -1, t: 1, o: 0 }, g: 0 }, right: { label: "포자 밀도 저감 작업 (소각)", fx: { c: 0, r: -2, t: 0, o: 1 }, g: 1 } },
  // ── 추가 카드: 기지 운영 + 탈북자 ──
  { id: "C-048", act: [1,2,3], priority: "중", msg: "신원불명의 무리가 기지 인근을 배회하고 있습니다.\n\n감시 카메라 기준 4~5명. 무장 여부 불명. 방향 없이 서성이고 있습니다.\n\n[ORACLE: 민간인 또는 비조직 유랑민으로 추정. 대응 지침을 결정하십시오.]", left: { label: "접근금지 경고", fx: { c: 0, r: 0, t: 1, o: 0 }, g: 0 }, right: { label: "요원 출동 제지", fx: { c: 1, r: -1, t: 0, o: 1 }, g: 1 } },
  { id: "C-049", act: [1,2,3], priority: "하", msg: "ORACLE이 전 요원 대상 위기 대응 훈련을 권고합니다.\n\n[ORACLE: 봉쇄선 돌파 시나리오 기준. 예상 소요: 반일. 훈련 중 봉쇄 감시 인원 50% 감소.]\n\n강도윤: \"필요한 훈련입니다. 하지만 타이밍이...\"", left: { label: "실시하라", fx: { c: -1, r: -1, t: 1, o: 1 }, g: 1 }, right: { label: "잠시 보류", fx: { c: 0, r: 0, t: 0, o: -1 }, g: -1 } },
  { id: "C-050", act: [2], priority: "중", req: (s) => s.day >= 3, msg: "봉쇄 구역 외곽에서 미확인 운송 차량이 무인 상태로 발견되었습니다.\n\n적재물: 의약품, 비상식량, 통신 장비. 발신자 불명. 표식 없음.\n\n서하은: \"누군가 우리에게 보낸 것일 수도 있습니다. 하지만 함정일 수도 있습니다.\"", left: { label: "물자 확보", fx: { c: 0, r: 2, t: 0, o: -1 }, g: -2 }, right: { label: "작전 중지. 접근 금지", fx: { c: 0, r: 0, t: 0, o: 1 }, g: 1 } },
  { id: "C-051", act: [2], priority: "상", req: (s) => s.day >= 5, msg: "봉쇄선 북측에서 신원미상의 인물이 양손을 든 채 접근하고 있습니다.\n\n무장 없음. 극도로 지친 상태. 반복적으로 무언가를 외치고 있습니다.\n\n강도윤: \"항복 의사로 보입니다. 어떻게 합니까?\"", left: { label: "직접 확인한다", fx: { c: 0, r: 0, t: 0, o: -1 }, g: -1 }, right: { label: "ORACLE에 보고", fx: { c: 0, r: 0, t: 0, o: 1 }, g: 2 } },
];
